### ISSUE TITLE
Leveln geht nicht mehr

### ISSUE THREAD

**Issue by jomo** [FluffyFishGames/JuhNau-Darkmode#1]
man bekommt nur noch coins :cry:

**Comment by FluffyFishGames** [comment]
Die neue Version umgeht das Problem und verteilt noch mehr Liebe! :)

**Comment by jomo** [comment]
:+1: :+1: :+1: :heart: liebe

**Comment by jomo** [comment]
Hab das gerade getestet, scheint aber nicht zu funktionieren :/
Ich lass den liker immer für ca 1 Minute laufen. Mach ich was falsch?

**Comment by jomo** [comment]
nvm, geht doch. Man muss nur warten bis man so viele coins hat wie in `Bescherung` eingetragen sind. Dauert halt ein bisschen :+1: :100:

**Comment by FluffyFishGames** [comment]
Richtig. Einfach laufen lassen, das Script erledigt den Rest.
